/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 newspaper.gltf 
Author: OswaldFan001 (https://sketchfab.com/Oswald001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/newspaper-edc62fa0997e406a8866d5d8c55692e2
Title: Newspaper
*/

import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'

export default function Newspaper(props) {
  const { nodes, materials } = useGLTF('/newspaper.gltf')

  const groupRef = useRef()
  
    // Rotate the model continuously
    useFrame(() => {
      if (groupRef.current) {
        groupRef.current.rotation.y += 0.01 // Adjust speed if needed
      }
    })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube_0.geometry} material={materials.Material} rotation={[0.29, -0.016, -0.058]} />
      </group>
    </group>
  )
}

useGLTF.preload('/newspaper.gltf')
