/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 painting.gltf 
Author: alban (https://sketchfab.com/alban)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bob-ross-painting-00a57bbd1c894a7cb9e45ec396a8f660
Title: Bob Ross painting
*/

import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { useRef } from "react";

export default function Painting(props) {
  const { nodes, materials } = useGLTF("/painting.gltf");

  const groupRef = useRef();

  // Rotate the model continuously
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.01; // Adjust speed if needed
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.material_0}
        rotation={[Math.PI / 10, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/painting.gltf");
